DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS vod;

CREATE TABLE user(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE vod (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	stream_preview_source TEXT NOT NULL,
	stream_source TEXT NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id)
);